import {
  IconAdjustments,
  IconAlertCircle,
  IconApps,
  IconAt,
  IconAtom,
  IconBell,
  IconBolt,
  IconBook,
  IconBook2,
  IconBookmark,
  IconBrandFigma,
  IconBrandGithub,
  IconBrandGitlab,
  IconBrandGoogle,
  IconBrandLinkedin,
  IconBrandSlack,
  IconBrandX,
  IconBrandYoutube,
  IconBriefcase,
  IconBrush,
  IconBuilding,
  IconBuildingStore,
  IconBulb,
  IconCalendar,
  IconCalendarEvent,
  IconCamera,
  IconCertificate,
  IconChartBar,
  IconChartDots,
  IconChartLine,
  IconChartPie,
  IconCheckbox,
  IconChecklist,
  IconClipboard,
  IconClipboardList,
  IconClock,
  IconCloud,
  IconCloudUpload,
  IconCode,
  IconCoin,
  IconCompass,
  IconCreditCard,
  IconCurrencyDollar,
  IconDatabase,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconFile,
  IconFileText,
  IconFiles,
  IconFilter,
  IconFlag,
  IconFlame,
  IconFlask,
  IconFolder,
  IconFolders,
  IconGift,
  IconHash,
  IconHeadphones,
  IconHeart,
  IconHelp,
  IconHelpCircle,
  IconHome,
  IconHome2,
  IconId,
  IconInfoCircle,
  IconKey,
  IconLayoutGrid,
  IconLink,
  IconList,
  IconListCheck,
  IconLock,
  IconMail,
  IconMailOpened,
  IconMap,
  IconMap2,
  IconMapPin,
  IconMessage,
  IconMessageCircle,
  IconMessages,
  IconMicroscope,
  IconMoodSmile,
  IconMusic,
  IconNews,
  IconNote,
  IconNotebook,
  IconNotes,
  IconPalette,
  IconPaperclip,
  IconPencil,
  IconPhone,
  IconPhoto,
  IconPin,
  IconPresentation,
  IconPuzzle,
  IconReport,
  IconRocket,
  IconRoute,
  IconRss,
  IconSchool,
  IconSearch,
  IconSend,
  IconServer,
  IconServer2,
  IconSettings,
  IconShare,
  IconShield,
  IconShoppingCart,
  IconStack,
  IconStar,
  IconTag,
  IconTags,
  IconTarget,
  IconTerminal,
  IconTerminal2,
  IconThumbUp,
  IconTicket,
  IconTool,
  IconTools,
  IconTrophy,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUsers,
  IconVideo,
  IconWand,
  IconWorld,
  IconWorldWww,
  IconZoom,
  type TablerIcon,
} from "@tabler/icons-react";

/**
 * Curated icon set for space custom links.
 *
 * Keep the identifiers in sync with the server allow-list at
 * apps/server/src/core/space/dto/update-space.dto.ts (SPACE_CUSTOM_LINK_ICONS).
 */
export const CUSTOM_LINK_ICONS: Record<string, TablerIcon> = {
  link: IconLink,
  "external-link": IconExternalLink,
  world: IconWorld,
  "world-www": IconWorldWww,
  book: IconBook,
  book2: IconBook2,
  notebook: IconNotebook,
  file: IconFile,
  "file-text": IconFileText,
  files: IconFiles,
  folder: IconFolder,
  folders: IconFolders,
  star: IconStar,
  home: IconHome,
  home2: IconHome2,
  settings: IconSettings,
  adjustments: IconAdjustments,
  tool: IconTool,
  tools: IconTools,
  users: IconUsers,
  user: IconUser,
  "user-circle": IconUserCircle,
  calendar: IconCalendar,
  "calendar-event": IconCalendarEvent,
  clock: IconClock,
  mail: IconMail,
  "mail-opened": IconMailOpened,
  message: IconMessage,
  "message-circle": IconMessageCircle,
  messages: IconMessages,
  bell: IconBell,
  bookmark: IconBookmark,
  flag: IconFlag,
  heart: IconHeart,
  "thumb-up": IconThumbUp,
  help: IconHelp,
  "help-circle": IconHelpCircle,
  "info-circle": IconInfoCircle,
  "alert-circle": IconAlertCircle,
  clipboard: IconClipboard,
  "clipboard-list": IconClipboardList,
  checklist: IconChecklist,
  checkbox: IconCheckbox,
  list: IconList,
  "list-check": IconListCheck,
  "chart-bar": IconChartBar,
  "chart-line": IconChartLine,
  "chart-pie": IconChartPie,
  "chart-dots": IconChartDots,
  database: IconDatabase,
  server: IconServer,
  server2: IconServer2,
  cloud: IconCloud,
  "cloud-upload": IconCloudUpload,
  code: IconCode,
  terminal: IconTerminal,
  terminal2: IconTerminal2,
  rocket: IconRocket,
  bulb: IconBulb,
  target: IconTarget,
  trophy: IconTrophy,
  flame: IconFlame,
  bolt: IconBolt,
  key: IconKey,
  lock: IconLock,
  shield: IconShield,
  tag: IconTag,
  tags: IconTags,
  paperclip: IconPaperclip,
  pin: IconPin,
  map: IconMap,
  "map-pin": IconMapPin,
  map2: IconMap2,
  phone: IconPhone,
  video: IconVideo,
  camera: IconCamera,
  photo: IconPhoto,
  music: IconMusic,
  headphones: IconHeadphones,
  download: IconDownload,
  upload: IconUpload,
  share: IconShare,
  send: IconSend,
  search: IconSearch,
  filter: IconFilter,
  edit: IconEdit,
  pencil: IconPencil,
  briefcase: IconBriefcase,
  building: IconBuilding,
  "shopping-cart": IconShoppingCart,
  "credit-card": IconCreditCard,
  coin: IconCoin,
  "currency-dollar": IconCurrencyDollar,
  gift: IconGift,
  ticket: IconTicket,
  presentation: IconPresentation,
  report: IconReport,
  news: IconNews,
  rss: IconRss,
  "brand-github": IconBrandGithub,
  "brand-gitlab": IconBrandGitlab,
  "brand-slack": IconBrandSlack,
  "brand-figma": IconBrandFigma,
  "brand-google": IconBrandGoogle,
  "brand-youtube": IconBrandYoutube,
  "brand-x": IconBrandX,
  "brand-linkedin": IconBrandLinkedin,
  palette: IconPalette,
  brush: IconBrush,
  wand: IconWand,
  puzzle: IconPuzzle,
  atom: IconAtom,
  flask: IconFlask,
  microscope: IconMicroscope,
  school: IconSchool,
  certificate: IconCertificate,
  id: IconId,
  notes: IconNotes,
  note: IconNote,
  stack: IconStack,
  "layout-grid": IconLayoutGrid,
  apps: IconApps,
  compass: IconCompass,
  route: IconRoute,
  "building-store": IconBuildingStore,
  "mood-smile": IconMoodSmile,
  eye: IconEye,
  zoom: IconZoom,
  hash: IconHash,
  at: IconAt,
};

export const CUSTOM_LINK_ICON_NAMES = Object.keys(CUSTOM_LINK_ICONS);

export const DEFAULT_CUSTOM_LINK_ICON = "link";

export function getCustomLinkIcon(name?: string): TablerIcon {
  return (name && CUSTOM_LINK_ICONS[name]) || IconLink;
}
