import { AiQuickCommand } from "@/features/ai/types/ai.types.ts";

export type BuiltInAiQuickCommand = AiQuickCommand & {
  translationKey: string;
  promptTranslationKey: string;
  descriptionTranslationKey: string;
};

export const DEFAULT_AI_QUICK_COMMANDS: BuiltInAiQuickCommand[] = [
  {
    id: "summarize",
    label: "Summarize",
    translationKey: "ai.commandSummarize",
    promptTranslationKey: "ai.commandPrompt.summarize",
    descriptionTranslationKey: "ai.commandDescription.summarize",
    prompt: "Summarize this content.",
    description: "Creates a concise summary of the selected context.",
    enabled: true,
    position: 0,
  },
  {
    id: "shorten",
    label: "Shorten",
    translationKey: "ai.commandShorten",
    promptTranslationKey: "ai.commandPrompt.shorten",
    descriptionTranslationKey: "ai.commandDescription.shorten",
    prompt: "Shorten this content while preserving its meaning.",
    description: "Makes the text shorter without losing its meaning.",
    enabled: true,
    position: 1,
  },
  {
    id: "explain",
    label: "Explain",
    translationKey: "ai.commandExplain",
    promptTranslationKey: "ai.commandPrompt.explain",
    descriptionTranslationKey: "ai.commandDescription.explain",
    prompt: "Explain this content clearly.",
    description: "Explains the text in clear, accessible language.",
    enabled: true,
    position: 2,
  },
  {
    id: "improve",
    label: "Improve",
    translationKey: "ai.commandImprove",
    promptTranslationKey: "ai.commandPrompt.improve",
    descriptionTranslationKey: "ai.commandDescription.improve",
    prompt: "Improve the clarity and structure of this content.",
    description: "Improves clarity, flow, and structure.",
    enabled: true,
    position: 3,
  },
  {
    id: "grammar",
    label: "Fix grammar",
    translationKey: "ai.commandGrammar",
    promptTranslationKey: "ai.commandPrompt.grammar",
    descriptionTranslationKey: "ai.commandDescription.grammar",
    prompt: "Fix grammar, spelling, and punctuation.",
    description: "Corrects grammar, spelling, and punctuation.",
    enabled: true,
    position: 4,
  },
  {
    id: "expand",
    label: "Expand",
    translationKey: "ai.commandExpand",
    promptTranslationKey: "ai.commandPrompt.expand",
    descriptionTranslationKey: "ai.commandDescription.expand",
    prompt: "Expand this content with useful detail.",
    description: "Adds useful detail while keeping the original intent.",
    enabled: true,
    position: 5,
  },
  {
    id: "continue",
    label: "Continue",
    translationKey: "ai.commandContinue",
    promptTranslationKey: "ai.commandPrompt.continue",
    descriptionTranslationKey: "ai.commandDescription.continue",
    prompt: "Continue writing from where the document ends.",
    description: "Continues writing in the style of the current document.",
    enabled: true,
    position: 6,
  },
  {
    id: "tone",
    label: "Change tone",
    translationKey: "ai.commandTone",
    promptTranslationKey: "ai.commandPrompt.tone",
    descriptionTranslationKey: "ai.commandDescription.tone",
    prompt: "Rewrite this content in a clear, professional tone.",
    description: "Rewrites the text in a clear professional tone.",
    enabled: true,
    position: 7,
  },
  {
    id: "translate",
    label: "Translate",
    translationKey: "ai.commandTranslate",
    promptTranslationKey: "ai.commandPrompt.translate",
    descriptionTranslationKey: "ai.commandDescription.translate",
    prompt: "Translate this content into the language I specify.",
    description: "Translates the text into the requested language.",
    enabled: true,
    position: 8,
  },
];
