/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AiAuxRuns {
  attemptNo: Generated<number>;
  cancelRequestedAt: Timestamp | null;
  clientRequestId: string | null;
  commandId: string | null;
  completedAt: Timestamp | null;
  conversationId: string | null;
  createdAt: Generated<Timestamp>;
  enqueuedAt: Timestamp | null;
  errorCode: string | null;
  expiresAt: Generated<Timestamp>;
  heartbeatAt: Timestamp | null;
  id: Generated<string>;
  inputSnapshot: string | null;
  inputTokens: Generated<Int8>;
  instruction: string | null;
  kind: string;
  outputTokens: Generated<Int8>;
  pageId: string;
  requestFingerprint: string;
  reservedTokens: Generated<Int8>;
  responseSnapshot: Generated<string>;
  resultTitle: string | null;
  selectionFrom: number | null;
  selectionText: string | null;
  selectionTo: number | null;
  sequence: Generated<number>;
  snapshotHash: string | null;
  sourceRunId: string | null;
  spaceId: string;
  startedAt: Timestamp | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface AiChatFiles {
  contentSha256: string | null;
  conversationId: string;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  error: string | null;
  extractedText: string | null;
  extractionStartedAt: Timestamp | null;
  id: Generated<string>;
  mimeType: string;
  name: string;
  size: Int8;
  spaceId: string;
  status: Generated<string>;
  storageDeletedAt: Timestamp | null;
  storageKey: string;
  updatedAt: Generated<Timestamp>;
  uploadBatchId: string | null;
  uploadedAt: Timestamp | null;
  uploadOrdinal: number | null;
  userId: string;
  workspaceId: string;
}

export interface AiConversationContextSources {
  conversationId: string;
  createdAt: Generated<Timestamp>;
  descendantMode: Generated<string>;
  id: Generated<string>;
  pageId: string;
  position: number;
  selectedDescendantPageIds: Generated<string[]>;
  sourceId: string;
  sourceType: string;
  updatedAt: Generated<Timestamp>;
}

export interface AiConversations {
  agentMode: Generated<boolean>;
  clientRequestId: string | null;
  contextAttachmentIds: Generated<string[]>;
  contextChatFileIds: Generated<string[]>;
  contextFingerprint: Generated<string>;
  contextRevision: Generated<number>;
  createdAt: Generated<Timestamp>;
  currentDocumentDescendantMode: Generated<string>;
  currentDocumentSelectedPageIds: Generated<string[]>;
  deletedAt: Timestamp | null;
  draft: string | null;
  id: Generated<string>;
  includeCurrentDocument: Generated<boolean>;
  lastOpenedAt: Generated<Timestamp>;
  pageId: string;
  promptHistoryCutoffAt: Timestamp | null;
  requestFingerprint: string | null;
  spaceId: string;
  title: string | null;
  titleSource: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
  useSpaceSearch: Generated<boolean>;
  workspaceId: string;
}

export interface AiFileUploadBatches {
  conversationId: string;
  createdAt: Generated<Timestamp>;
  errorCode: string | null;
  id: Generated<string>;
  idempotencyKey: string;
  requestFingerprint: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface AiMessages {
  clientRequestId: string | null;
  content: Generated<string>;
  conversationId: string;
  createdAt: Generated<Timestamp>;
  currentRunId: string | null;
  errorCode: string | null;
  errorMessage: string | null;
  id: Generated<string>;
  inputTokens: Generated<Int8>;
  outputTokens: Generated<Int8>;
  reasoning: Generated<string>;
  role: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
  workspaceId: string;
}

export interface AiMessageSources {
  createdAt: Generated<Timestamp>;
  excerpt: string | null;
  id: Generated<string>;
  messageId: string;
  pageId: string | null;
  position: number;
  relevanceScore: number | null;
  runId: string;
  sourceId: string;
  sourceTitle: string;
  sourceType: string;
  sourceUrl: string | null;
}

export interface AiRunContextSources {
  contentSha256: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  markdownSnapshot: string;
  origin: string;
  pageId: string;
  position: number;
  runId: string;
  sourceId: string;
  sourceTitle: string;
  sourceType: string;
  sourceUrl: string | null;
}

export interface AiRuns {
  assistantMessageId: string;
  attachmentIds: Generated<string[]>;
  attemptNo: Generated<number>;
  cancelRequestedAt: Timestamp | null;
  chatFileIds: Generated<string[]>;
  clientRequestId: string;
  completedAt: Timestamp | null;
  contextRevision: Generated<number>;
  conversationId: string;
  createdAt: Generated<Timestamp>;
  documentSnapshot: string | null;
  enqueuedAt: Timestamp | null;
  errorCode: string | null;
  errorMessage: string | null;
  executionMode: Generated<string>;
  finishReason: string | null;
  heartbeatAt: Timestamp | null;
  id: Generated<string>;
  inputTokens: Generated<Int8>;
  outputTokens: Generated<Int8>;
  pageId: string;
  previousRunId: string | null;
  reasoningSnapshot: string | null;
  requestFingerprint: string | null;
  reservedTokens: Generated<Int8>;
  responseSnapshot: string | null;
  retrievalErrorCode: string | null;
  retrievalOutcome: Generated<string>;
  rootRunId: string;
  selectionFrom: number | null;
  selectionText: string | null;
  selectionTo: number | null;
  sequence: Generated<number>;
  snapshotHash: string | null;
  spaceId: string;
  startedAt: Timestamp | null;
  status: Generated<string>;
  trigger: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  userMessageId: string;
  useSpaceSearch: Generated<boolean>;
  workspaceId: string;
}

export interface AiRunSteps {
  arguments: Json;
  assistantContent: string | null;
  baseContentHash: string | null;
  callIndex: number;
  createdAt: Generated<Timestamp>;
  decidedAt: Timestamp | null;
  decidedById: string | null;
  errorCode: string | null;
  errorMessage: string | null;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  modelStep: number;
  result: Json | null;
  runId: string;
  sequence: number;
  status: string;
  targetPageId: string | null;
  toolCallId: string;
  toolName: string;
  updatedAt: Generated<Timestamp>;
  writeClass: string;
}

export interface AiRunSourceDependencies {
  contextSourceId: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  messageId: string;
  pageId: string;
  runId: string;
}

export interface AiSpaceConfigs {
  agentEnabled: Generated<boolean>;
  agentVerifiedAt: Timestamp | null;
  agentVerifiedProviderFingerprint: string | null;
  apiKeyEncrypted: string | null;
  assistantGender: Generated<string>;
  assistantName: string | null;
  assistantNameEnabled: Generated<boolean>;
  baseUrl: string;
  chatModel: string;
  contextWindow: Generated<number>;
  createdAt: Generated<Timestamp>;
  createdById: string | null;
  dailyRequestLimitPerUser: Generated<number>;
  dailyTokenLimitPerSpace: Generated<Int8>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  maxOutputTokens: Generated<number>;
  provider: Generated<string>;
  quickCommands: Json | null;
  reasoningEnabled: Generated<boolean>;
  requestTimeoutMs: Generated<number>;
  retentionDays: Generated<number>;
  retrievalAdapter: Generated<string>;
  retrievalApiKeyEncrypted: string | null;
  retrievalMaxResults: Generated<number>;
  retrievalOpenWebuiApiKeyEncrypted: string | null;
  retrievalOpenWebuiBaseUrl: string | null;
  retrievalOpenWebuiKnowledgeId: string | null;
  retrievalTimeoutMs: Generated<number>;
  retrievalUrl: string | null;
  spaceId: string;
  systemInstructions: string | null;
  temperature: Generated<number>;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  visionEnabled: Generated<boolean>;
  workspaceId: string;
}

export interface AiSpaceContentExclusions {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  includeDescendants: Generated<boolean>;
  pageId: string;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface AiSpaceContentPolicies {
  createdAt: Generated<Timestamp>;
  fingerprint: Generated<string>;
  revision: Generated<number>;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface ApiKeys {
  createdAt: Generated<Timestamp>;
  creatorId: string;
  deletedAt: Timestamp | null;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  keyType: Generated<string>;
  lastUsedAt: Timestamp | null;
  name: string;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Attachments {
  createdAt: Generated<Timestamp>;
  creatorId: string;
  deletedAt: Timestamp | null;
  fileExt: string;
  fileName: string;
  filePath: string;
  fileSize: Int8 | null;
  id: Generated<string>;
  mimeType: string | null;
  pageId: string | null;
  spaceId: string | null;
  textContent: string | null;
  tsv: string | null;
  type: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface AuthAccounts {
  authProviderId: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  providerUserId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface AuthProviders {
  allowSignup: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  groupSync: Generated<boolean>;
  id: Generated<string>;
  isEnabled: Generated<boolean>;
  ldapBaseDn: string | null;
  ldapBindDn: string | null;
  ldapBindPassword: string | null;
  ldapConfig: Generated<Json | null>;
  ldapTlsCaCert: string | null;
  ldapTlsEnabled: Generated<boolean | null>;
  ldapUrl: string | null;
  ldapUserAttributes: Generated<Json | null>;
  ldapUserSearchFilter: string | null;
  lastErrorCode: string | null;
  lastSuccessfulLoginAt: Timestamp | null;
  name: string;
  oidcClientId: string | null;
  oidcClientSecret: string | null;
  oidcIssuer: string | null;
  samlCertificate: string | null;
  samlUrl: string | null;
  settings: Generated<Json | null>;
  type: string;
  updatedAt: Generated<Timestamp>;
  verifiedAt: Timestamp | null;
  workspaceId: string;
}

export interface AuthProviderGroupMappings {
  authProviderId: string;
  createdAt: Generated<Timestamp>;
  externalGroupId: string;
  groupId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface AuthProviderGroupMemberships {
  authProviderId: string;
  createdAt: Generated<Timestamp>;
  groupId: string;
  id: Generated<string>;
  ownsGroupMembership: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Backlinks {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  sourcePageId: string;
  targetPageId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Comments {
  content: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  editedAt: Timestamp | null;
  id: Generated<string>;
  lastEditedById: string | null;
  pageId: string;
  parentCommentId: string | null;
  resolvedAt: Timestamp | null;
  resolvedById: string | null;
  selection: string | null;
  spaceId: string;
  type: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface DatabaseCells {
  attachmentId: string | null;
  createdAt: Generated<Timestamp>;
  createdById: string | null;
  databaseId: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  pageId: string;
  propertyId: string;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  value: Json | null;
  workspaceId: string;
}

export interface DatabaseProperties {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  databaseId: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  position: Generated<number>;
  settings: Json | null;
  type: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface DatabaseRows {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  createdById: string | null;
  databaseId: string;
  id: Generated<string>;
  pageId: string;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  workspaceId: string;
}

export interface Databases {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  descriptionContent: Json | null;
  icon: string | null;
  id: Generated<string>;
  lastUpdatedById: string | null;
  name: string;
  pageId: string | null;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface DatabaseViews {
  config: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  databaseId: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  type: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface DictionaryTermAliases {
  alias: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isPrimary: Generated<boolean>;
  normalizedAlias: string;
  spaceId: string;
  termId: string;
  workspaceId: string;
}

export interface DictionaryTerms {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  definitionMarkdown: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  spaceId: string;
  term: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Favorites {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  pageId: string | null;
  spaceId: string | null;
  type: string;
  userId: string;
  workspaceId: string;
}

export interface FileTasks {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  errorMessage: string | null;
  fileExt: string | null;
  fileName: string;
  filePath: string;
  fileSize: Int8 | null;
  id: Generated<string>;
  options: Json | null;
  result: Json | null;
  source: string | null;
  spaceId: string | null;
  status: string | null;
  type: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Groups {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  isDefault: boolean;
  name: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface GroupUsers {
  createdAt: Generated<Timestamp>;
  groupId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Labels {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  spaceId: string;
  type: Generated<string>;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Notifications {
  actorId: string | null;
  archivedAt: Timestamp | null;
  commentId: string | null;
  createdAt: Generated<Timestamp>;
  data: Json | null;
  emailedAt: Timestamp | null;
  id: Generated<string>;
  pageId: string | null;
  readAt: Timestamp | null;
  spaceId: string | null;
  type: string;
  userId: string;
  workspaceId: string;
}

export interface PageAccessRules {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  effect: string;
  groupId: string | null;
  id: Generated<string>;
  pageId: string;
  principalType: string;
  role: string | null;
  sourcePageId: string | null;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  userId: string | null;
  workspaceId: string;
}

export interface PageHistory {
  changeData: Json | null;
  changeType: string | null;
  content: Json | null;
  contributorIds: Generated<string[] | null>;
  coverPhoto: string | null;
  createdAt: Generated<Timestamp>;
  icon: string | null;
  id: Generated<string>;
  lastUpdatedById: string | null;
  pageId: string;
  slug: string | null;
  slugId: string | null;
  spaceId: string;
  title: string | null;
  updatedAt: Generated<Timestamp>;
  version: number | null;
  workspaceId: string;
}

export interface PageLabels {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  labelId: string;
  pageId: string;
}

export interface Pages {
  content: Json | null;
  contributorIds: Generated<string[] | null>;
  coverPhoto: string | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  deletedById: string | null;
  icon: string | null;
  id: Generated<string>;
  isLocked: Generated<boolean>;
  lastUpdatedById: string | null;
  parentPageId: string | null;
  position: string | null;
  settings: Generated<Json | null>;
  slugId: string;
  spaceId: string;
  textContent: string | null;
  title: string | null;
  tsv: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
  ydoc: Buffer | null;
}

export interface PageTransclusionReferences {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  referencePageId: string;
  sourcePageId: string;
  transclusionId: string;
  workspaceId: string;
}

export interface PageTransclusions {
  content: Json;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  pageId: string;
  transclusionId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface PushNotificationJobs {
  createdAt: Generated<Timestamp>;
  eventsCount: Generated<number>;
  id: Generated<string>;
  idempotencyKey: string;
  pageId: string;
  payload: Json | null;
  sendAfter: Timestamp;
  sentAt: Timestamp | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  windowKey: string;
  workspaceId: string;
}

export interface PushSubscriptions {
  auth: string;
  createdAt: Generated<Timestamp>;
  endpoint: string;
  id: Generated<string>;
  lastSeenAt: Generated<Timestamp>;
  p256dh: string;
  revokedAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
  workspaceId: string;
}

export interface Shares {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  includeSubPages: Generated<boolean | null>;
  key: string;
  pageId: string | null;
  searchIndexing: Generated<boolean | null>;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface SsoLoginStates {
  authProviderId: string;
  codeVerifier: string | null;
  consumedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  nonce: string | null;
  requestId: string | null;
  requestValue: string | null;
  stateHash: string;
  workspaceId: string;
}

export interface SpaceMembers {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  groupId: string | null;
  id: Generated<string>;
  role: string;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
}

export interface Spaces {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  defaultRole: Generated<string>;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  logo: string | null;
  name: string | null;
  settings: Json | null;
  slug: string;
  updatedAt: Generated<Timestamp>;
  visibility: Generated<string>;
  workspaceId: string;
}

export interface UserMfa {
  backupCodes: string[] | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isEnabled: Generated<boolean | null>;
  method: Generated<string>;
  secret: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  deactivatedAt: Timestamp | null;
  deletedAt: Timestamp | null;
  email: string;
  emailVerifiedAt: Timestamp | null;
  hasGeneratedPassword: Generated<boolean>;
  id: Generated<string>;
  invitedById: string | null;
  lastActiveAt: Timestamp | null;
  lastLoginAt: Timestamp | null;
  locale: string | null;
  name: string | null;
  password: string | null;
  role: string | null;
  settings: Json | null;
  timezone: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string | null;
}

export interface UserSessions {
  createdAt: Generated<Timestamp>;
  deviceName: string | null;
  expiresAt: Timestamp;
  geoLocation: string | null;
  id: Generated<string>;
  ipAddress: string | null;
  lastActiveAt: Generated<Timestamp>;
  metadata: Json | null;
  revokedAt: Timestamp | null;
  userAgent: string | null;
  userId: string;
  workspaceId: string;
}

export interface UserTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  token: string;
  type: string;
  usedAt: Timestamp | null;
  userId: string;
  workspaceId: string | null;
}

export interface Watchers {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  mutedAt: Timestamp | null;
  pageId: string | null;
  spaceId: string;
  type: string;
  userId: string;
  workspaceId: string;
}

export interface WorkspaceInvitations {
  createdAt: Generated<Timestamp>;
  email: string | null;
  expiresAt: Timestamp | null;
  groupIds: string[] | null;
  id: Generated<string>;
  invitedById: string | null;
  role: string;
  token: string | null;
  tokenHash: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Workspaces {
  createdAt: Generated<Timestamp>;
  customDomain: string | null;
  defaultRole: Generated<string>;
  defaultSpaceId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  emailDomains: Generated<string[] | null>;
  enforceMfa: Generated<boolean | null>;
  enforceSso: Generated<boolean>;
  hostname: string | null;
  id: Generated<string>;
  logo: string | null;
  name: string | null;
  settings: Json | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  aiAuxRuns: AiAuxRuns;
  aiChatFiles: AiChatFiles;
  aiConversationContextSources: AiConversationContextSources;
  aiConversations: AiConversations;
  aiFileUploadBatches: AiFileUploadBatches;
  aiMessages: AiMessages;
  aiMessageSources: AiMessageSources;
  aiRunContextSources: AiRunContextSources;
  aiRuns: AiRuns;
  aiRunSteps: AiRunSteps;
  aiRunSourceDependencies: AiRunSourceDependencies;
  aiSpaceConfigs: AiSpaceConfigs;
  aiSpaceContentExclusions: AiSpaceContentExclusions;
  aiSpaceContentPolicies: AiSpaceContentPolicies;
  apiKeys: ApiKeys;
  attachments: Attachments;
  authAccounts: AuthAccounts;
  authProviderGroupMappings: AuthProviderGroupMappings;
  authProviderGroupMemberships: AuthProviderGroupMemberships;
  authProviders: AuthProviders;
  backlinks: Backlinks;
  comments: Comments;
  databaseCells: DatabaseCells;
  databaseProperties: DatabaseProperties;
  databaseRows: DatabaseRows;
  databases: Databases;
  databaseViews: DatabaseViews;
  dictionaryTermAliases: DictionaryTermAliases;
  dictionaryTerms: DictionaryTerms;
  favorites: Favorites;
  fileTasks: FileTasks;
  groups: Groups;
  groupUsers: GroupUsers;
  labels: Labels;
  notifications: Notifications;
  pageAccessRules: PageAccessRules;
  pageHistory: PageHistory;
  pageLabels: PageLabels;
  pages: Pages;
  pageTransclusionReferences: PageTransclusionReferences;
  pageTransclusions: PageTransclusions;
  pushNotificationJobs: PushNotificationJobs;
  pushSubscriptions: PushSubscriptions;
  shares: Shares;
  spaceMembers: SpaceMembers;
  spaces: Spaces;
  ssoLoginStates: SsoLoginStates;
  userMfa: UserMfa;
  users: Users;
  userSessions: UserSessions;
  userTokens: UserTokens;
  watchers: Watchers;
  workspaceInvitations: WorkspaceInvitations;
  workspaces: Workspaces;
}
