/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AiAuxRuns {
  attemptNo: Generated<number>;
  cancelRequestedAt: Timestamp | null;
  clientRequestId: string | null;
  commandId: string | null;
  completedAt: Timestamp | null;
  conversationId: string | null;
  createdAt: Generated<Timestamp>;
  enqueuedAt: Timestamp | null;
  errorCode: string | null;
  expiresAt: Generated<Timestamp>;
  heartbeatAt: Timestamp | null;
  id: Generated<string>;
  inputSnapshot: string | null;
  inputTokens: Generated<Int8>;
  instruction: string | null;
  kind: string;
  outputTokens: Generated<Int8>;
  pageId: string;
  requestFingerprint: string;
  reservedTokens: Generated<Int8>;
  responseSnapshot: Generated<string>;
  resultTitle: string | null;
  selectionFrom: number | null;
  selectionText: string | null;
  selectionTo: number | null;
  sequence: Generated<number>;
  snapshotHash: string | null;
  sourceRunId: string | null;
  spaceId: string;
  startedAt: Timestamp | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface AiChatFiles {
  contentSha256: string | null;
  conversationId: string;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  error: string | null;
  extractedText: string | null;
  extractionStartedAt: Timestamp | null;
  id: Generated<string>;
  mimeType: string;
  name: string;
  size: Int8;
  spaceId: string;
  status: Generated<string>;
  storageDeletedAt: Timestamp | null;
  storageKey: string;
  updatedAt: Generated<Timestamp>;
  uploadBatchId: string | null;
  uploadedAt: Timestamp | null;
  uploadOrdinal: number | null;
  userId: string;
  workspaceId: string;
}

export interface AiConversationContextSources {
  conversationId: string;
  createdAt: Generated<Timestamp>;
  descendantMode: Generated<string>;
  id: Generated<string>;
  pageId: string;
  position: number;
  selectedDescendantPageIds: Generated<string[]>;
  sourceId: string;
  sourceType: string;
  updatedAt: Generated<Timestamp>;
}

export interface AiAgentToolVerifications {
  id: Generated<string>;
  probeToolName: string;
  profileId: string;
  profileVersion: number;
  providerFingerprint: string;
  spaceId: string;
  testedAt: Generated<Timestamp>;
  testedById: string | null;
  toolPolicyFingerprint: string;
  toolSchemaFingerprint: string;
  verificationFingerprint: string;
  workspaceId: string;
}

export interface AiAssistantProfileGroupPolicies {
  allowedBuiltinCapabilities: Json | null;
  available: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  createdById: string | null;
  groupId: string;
  id: Generated<string>;
  profileId: string;
  updatedAt: Generated<Timestamp>;
}

export interface AiAssistantProfileMcpTools {
  bindingId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  profileId: string;
  toolName: string;
}

export interface AiAssistantProfiles {
  allowedBuiltinCapabilities: Generated<Json>;
  autoStart: Generated<boolean>;
  chatModelOverride: string | null;
  createdAt: Generated<Timestamp>;
  createdById: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  enabled: Generated<boolean>;
  icon: string;
  id: Generated<string>;
  instructions: string;
  launchMessage: string | null;
  maxOutputTokensOverride: number | null;
  name: string;
  quickCommands: Json | null;
  spaceId: string;
  temperatureOverride: number | null;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  version: Generated<number>;
  workspaceId: string;
}

export interface AiAssistantProfileUserPreferences {
  createdAt: Generated<Timestamp>;
  hiddenProfileIds: Generated<string[]>;
  id: Generated<string>;
  preferredProfileId: string | null;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface AiAssistantProfileWorkspaceSettings {
  createdAt: Generated<Timestamp>;
  enabled: Generated<boolean>;
  modelOverridesEnabled: Generated<boolean>;
  policyVersion: Generated<number>;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  workspaceId: string;
}

export interface AiConversations {
  agentMode: Generated<boolean>;
  assistantProfileFingerprint: string | null;
  assistantProfileId: string | null;
  assistantProfileSnapshot: Json | null;
  assistantProfileVersion: number | null;
  clientRequestId: string | null;
  contextAttachmentIds: Generated<string[]>;
  contextChatFileIds: Generated<string[]>;
  contextFingerprint: Generated<string>;
  contextRevision: Generated<number>;
  createdAt: Generated<Timestamp>;
  currentDocumentDescendantMode: Generated<string>;
  currentDocumentSelectedPageIds: Generated<string[]>;
  deletedAt: Timestamp | null;
  draft: string | null;
  id: Generated<string>;
  includeCurrentDocument: Generated<boolean>;
  lastOpenedAt: Generated<Timestamp>;
  pageId: string;
  promptHistoryCutoffAt: Timestamp | null;
  requestFingerprint: string | null;
  spaceId: string;
  title: string | null;
  titleSource: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
  useSpaceSearch: Generated<boolean>;
  workspaceId: string;
}

export interface AiFileUploadBatches {
  conversationId: string;
  createdAt: Generated<Timestamp>;
  errorCode: string | null;
  id: Generated<string>;
  idempotencyKey: string;
  requestFingerprint: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface AiMcpGroupPolicies {
  allowedTools: Json | null;
  bindingId: string;
  createdAt: Generated<Timestamp>;
  createdById: string | null;
  denyConnection: Generated<boolean>;
  groupId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface AiMcpServers {
  approvedTools: Generated<Json>;
  configVersion: Generated<number>;
  createdAt: Generated<Timestamp>;
  createdById: string | null;
  discoveredAt: Timestamp | null;
  discoveredTools: Generated<Json>;
  discoveryToolCount: Generated<number>;
  enabled: Generated<boolean>;
  headerNames: Generated<Json>;
  headersEncrypted: string | null;
  id: Generated<string>;
  name: string;
  namespace: string;
  testCheckedAt: Timestamp | null;
  testErrorCode: string | null;
  testStatus: Generated<string>;
  transport: Generated<string>;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  url: string;
  workspaceId: string;
}

export interface AiMcpSpaceBindings {
  allowedTools: Generated<Json>;
  createdAt: Generated<Timestamp>;
  createdById: string | null;
  enabled: Generated<boolean>;
  id: Generated<string>;
  instructions: string | null;
  policyVersion: Generated<number>;
  profileAllowedTools: Generated<Json>;
  serverId: string;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  workspaceId: string;
}

export interface AiMcpUserPreferences {
  bindingId: string;
  createdAt: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface AiMcpWorkspaceSettings {
  allowedOrigins: Generated<string>;
  createdAt: Generated<Timestamp>;
  createdById: string | null;
  enabled: Generated<boolean>;
  id: Generated<string>;
  policyVersion: Generated<number>;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  workspaceId: string;
}

export interface AiMessages {
  clientRequestId: string | null;
  content: Generated<string>;
  conversationId: string;
  createdAt: Generated<Timestamp>;
  currentRunId: string | null;
  errorCode: string | null;
  errorMessage: string | null;
  id: Generated<string>;
  inputTokens: Generated<Int8>;
  outputTokens: Generated<Int8>;
  reasoning: Generated<string>;
  role: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
  workspaceId: string;
}

export interface AiMessageSources {
  candidateKey: string | null;
  citationKey: string | null;
  citationState: Generated<string>;
  createdAt: Generated<Timestamp>;
  displayPosition: number | null;
  excerpt: string | null;
  id: Generated<string>;
  messageId: string;
  pageId: string | null;
  position: number;
  relevanceScore: number | null;
  runId: string;
  sectionId: string | null;
  sectionTitle: string | null;
  sourceId: string;
  sourceTitle: string;
  sourceType: string;
  sourceUrl: string | null;
}

export interface AiRunContextSources {
  citationHeadings: Generated<unknown>;
  contentSha256: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  markdownSnapshot: string;
  origin: string;
  pageId: string;
  position: number;
  runId: string;
  sourceId: string;
  sourceTitle: string;
  sourceType: string;
  sourceUrl: string | null;
}

export interface AiBuiltinToolSpacePolicies {
  allowedCapabilities: Json | null;
  createdAt: Generated<Timestamp>;
  policyVersion: Generated<number>;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  workspaceId: string;
}

export interface AiBuiltinToolWorkspacePolicies {
  allowedCapabilities: Json;
  createdAt: Generated<Timestamp>;
  enabled: Generated<boolean>;
  policyVersion: Generated<number>;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  workspaceId: string;
}

export interface AiRuns {
  assistantMessageId: string;
  assistantProfileFingerprint: string | null;
  assistantProfileSnapshot: Json | null;
  attachmentIds: Generated<string[]>;
  attemptNo: Generated<number>;
  builtinToolPolicyFingerprint: string | null;
  builtinToolPolicySnapshot: Json | null;
  cancelRequestedAt: Timestamp | null;
  chatFileIds: Generated<string[]>;
  clientRequestId: string;
  completedAt: Timestamp | null;
  contextRevision: Generated<number>;
  conversationId: string;
  createdAt: Generated<Timestamp>;
  documentSnapshot: string | null;
  enqueuedAt: Timestamp | null;
  errorCode: string | null;
  errorMessage: string | null;
  executionMode: Generated<string>;
  finishReason: string | null;
  heartbeatAt: Timestamp | null;
  id: Generated<string>;
  inputTokens: Generated<Int8>;
  mcpPolicyFingerprint: string | null;
  mcpPolicySnapshot: Json | null;
  outputTokens: Generated<Int8>;
  pageId: string;
  previousRunId: string | null;
  providerConfigFingerprint: string | null;
  providerConfigSnapshot: Json | null;
  reasoningSnapshot: string | null;
  requestFingerprint: string | null;
  reservedTokens: Generated<Int8>;
  responseSnapshot: string | null;
  retrievalErrorCode: string | null;
  retrievalOutcome: Generated<string>;
  retrievalQuery: string | null;
  retrievalRewriteErrorCode: string | null;
  retrievalRewriteInputTokens: Generated<Int8>;
  retrievalRewriteLatencyMs: number | null;
  retrievalRewriteOutcome: Generated<string>;
  retrievalRewriteOutputTokens: Generated<Int8>;
  rootRunId: string;
  selectionFrom: number | null;
  selectionText: string | null;
  selectionTo: number | null;
  sequence: Generated<number>;
  snapshotHash: string | null;
  spaceId: string;
  startedAt: Timestamp | null;
  status: Generated<string>;
  trigger: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  userMessageId: string;
  useSpaceSearch: Generated<boolean>;
  workspaceId: string;
}

export interface AiRunSourceDependencies {
  contextSourceId: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  messageId: string;
  pageId: string;
  runId: string;
}

export interface AiRunSteps {
  arguments: Json;
  assistantContent: string | null;
  baseContentHash: string | null;
  callIndex: number;
  createdAt: Generated<Timestamp>;
  decidedAt: Timestamp | null;
  decidedById: string | null;
  errorCode: string | null;
  errorMessage: string | null;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  mcpConfigVersion: number | null;
  mcpServerId: string | null;
  mcpToolName: string | null;
  modelStep: number;
  result: Json | null;
  runId: string;
  sequence: number;
  status: string;
  targetPageId: string | null;
  toolCallId: string;
  toolName: string;
  toolSource: Generated<string>;
  updatedAt: Generated<Timestamp>;
  writeClass: string;
}

export interface AiSpaceConfigs {
  agentEnabled: Generated<boolean>;
  agentVerifiedAt: Timestamp | null;
  agentVerifiedProviderFingerprint: string | null;
  apiKeyEncrypted: string | null;
  assistantGender: Generated<string>;
  assistantName: string | null;
  assistantNameEnabled: Generated<boolean>;
  baseUrl: string;
  chatModel: string;
  contextWindow: Generated<number>;
  createdAt: Generated<Timestamp>;
  createdById: string | null;
  dailyRequestLimitPerUser: Generated<number>;
  dailyTokenLimitPerSpace: Generated<Int8>;
  defaultAssistantProfileId: string | null;
  enabled: Generated<boolean>;
  id: Generated<string>;
  maxOutputTokens: Generated<number>;
  provider: Generated<string>;
  quickCommands: Json | null;
  reasoningEnabled: Generated<boolean>;
  requestTimeoutMs: Generated<number>;
  retentionDays: Generated<number>;
  retrievalAdapter: Generated<string>;
  retrievalApiKeyEncrypted: string | null;
  retrievalMaxResults: Generated<number>;
  retrievalFollowUpRewriteEnabled: Generated<boolean>;
  retrievalOpenWebuiApiKeyEncrypted: string | null;
  retrievalOpenWebuiBaseUrl: string | null;
  retrievalOpenWebuiKnowledgeId: string | null;
  retrievalTimeoutMs: Generated<number>;
  retrievalQueryMode: Generated<string>;
  retrievalUrl: string | null;
  spaceId: string;
  systemInstructions: string | null;
  temperature: Generated<number>;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  visionEnabled: Generated<boolean>;
  workspaceId: string;
}

export interface AiSpaceContentExclusions {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  includeDescendants: Generated<boolean>;
  pageId: string;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface AiSpaceContentPolicies {
  createdAt: Generated<Timestamp>;
  fingerprint: Generated<string>;
  ragSearchDoneOnly: Generated<boolean>;
  revision: Generated<number>;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface RagSyncBindings {
  adapter: Generated<string>;
  baseUrl: string | null;
  cleanupRequired: Generated<boolean>;
  configVersion: Generated<number>;
  createdAt: Generated<Timestamp>;
  createdById: string | null;
  id: Generated<string>;
  knowledgeId: string | null;
  lastTestedAt: Timestamp | null;
  spaceId: string;
  state: Generated<string>;
  targetClaimId: string | null;
  targetVersion: Generated<number>;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  workspaceId: string;
  writerApiKeyEncrypted: string | null;
}

export interface RagSyncTargetClaims {
  bindingId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  spaceId: string;
  state: Generated<string>;
  targetFingerprint: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface ApiKeys {
  allowedCapabilities: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string;
  deletedAt: Timestamp | null;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  keyType: Generated<string>;
  lastUsedAt: Timestamp | null;
  name: string;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Attachments {
  contentIndexedAt: Timestamp | null;
  contentIndexError: string | null;
  contentIndexStartedAt: Timestamp | null;
  contentIndexStatus: string | null;
  contentIndexVersion: number | null;
  createdAt: Generated<Timestamp>;
  creatorId: string;
  deletedAt: Timestamp | null;
  fileExt: string;
  fileName: string;
  filePath: string;
  fileSize: Int8 | null;
  id: Generated<string>;
  mimeType: string | null;
  pageId: string | null;
  spaceId: string | null;
  textContent: string | null;
  tsv: string | null;
  type: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface AuthAccounts {
  authProviderId: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  providerUserId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface AuthProviderGroupMappings {
  authProviderId: string;
  createdAt: Generated<Timestamp>;
  externalGroupId: string;
  groupId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface AuthProviderGroupMemberships {
  authProviderId: string;
  createdAt: Generated<Timestamp>;
  groupId: string;
  id: Generated<string>;
  ownsGroupMembership: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface AuthProviders {
  allowSignup: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  groupSync: Generated<boolean>;
  id: Generated<string>;
  isEnabled: Generated<boolean>;
  lastErrorCode: string | null;
  lastSuccessfulLoginAt: Timestamp | null;
  ldapBaseDn: string | null;
  ldapBindDn: string | null;
  ldapBindPassword: string | null;
  ldapConfig: Generated<Json | null>;
  ldapTlsCaCert: string | null;
  ldapTlsEnabled: Generated<boolean | null>;
  ldapUrl: string | null;
  ldapUserAttributes: Generated<Json | null>;
  ldapUserSearchFilter: string | null;
  name: string;
  oidcClientId: string | null;
  oidcClientSecret: string | null;
  oidcIssuer: string | null;
  samlCertificate: string | null;
  samlUrl: string | null;
  settings: Generated<Json | null>;
  type: string;
  updatedAt: Generated<Timestamp>;
  verifiedAt: Timestamp | null;
  workspaceId: string;
}

export interface Backlinks {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  sourcePageId: string;
  targetPageId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface AttachmentCleanupBatches {
  completedAt: Timestamp | null;
  completedCount: Generated<number>;
  createdAt: Generated<Timestamp>;
  failedCount: Generated<number>;
  id: Generated<string>;
  itemCount: Generated<number>;
  leaseExpiresAt: Timestamp | null;
  leaseToken: string | null;
  scopeId: string;
  scopeType: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface AttachmentCleanupItems {
  attachmentId: string;
  attemptCount: Generated<number>;
  batchId: string;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  filePath: string;
  id: Generated<string>;
  lastErrorCode: string | null;
  leaseExpiresAt: Timestamp | null;
  leaseToken: string | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Comments {
  content: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  editedAt: Timestamp | null;
  id: Generated<string>;
  lastEditedById: string | null;
  pageId: string;
  parentCommentId: string | null;
  resolvedAt: Timestamp | null;
  resolvedById: string | null;
  selection: string | null;
  spaceId: string;
  type: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface DatabaseCells {
  attachmentId: string | null;
  createdAt: Generated<Timestamp>;
  createdById: string | null;
  databaseId: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  pageId: string;
  propertyId: string;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  value: Json | null;
  workspaceId: string;
}

export interface DatabaseProperties {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  databaseId: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  position: Generated<number>;
  settings: Json | null;
  type: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface DatabaseRows {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  createdById: string | null;
  databaseId: string;
  id: Generated<string>;
  pageId: string;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  workspaceId: string;
}

export interface Databases {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  descriptionContent: Json | null;
  icon: string | null;
  id: Generated<string>;
  lastUpdatedById: string | null;
  name: string;
  pageId: string | null;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface DatabaseViews {
  config: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  databaseId: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  type: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface DictionaryTermAliases {
  alias: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isPrimary: Generated<boolean>;
  normalizedAlias: string;
  spaceId: string;
  termId: string;
  workspaceId: string;
}

export interface DictionaryTerms {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  definitionMarkdown: string;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  spaceId: string;
  term: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Favorites {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  pageId: string | null;
  spaceId: string | null;
  type: string;
  userId: string;
  workspaceId: string;
}

export interface FileTasks {
  attemptCount: Generated<number>;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  errorMessage: string | null;
  fileExt: string | null;
  fileName: string;
  filePath: string;
  fileSize: Int8 | null;
  id: Generated<string>;
  leaseExpiresAt: Timestamp | null;
  leaseToken: string | null;
  options: Json | null;
  result: Json | null;
  source: string | null;
  spaceId: string | null;
  status: string | null;
  type: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface FileTaskImportArtifacts {
  artifactType: Generated<string>;
  attachmentId: string | null;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  filePath: string;
  fileTaskId: string;
  id: Generated<string>;
  pageId: string | null;
  sourcePath: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface FileTaskImportPages {
  createdAt: Generated<Timestamp>;
  fileTaskId: string;
  id: Generated<string>;
  pageId: string;
  slugId: string;
  sourcePath: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Groups {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  isDefault: boolean;
  name: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface GroupUsers {
  createdAt: Generated<Timestamp>;
  groupId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Labels {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  spaceId: string;
  type: Generated<string>;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Notifications {
  actorId: string | null;
  archivedAt: Timestamp | null;
  commentId: string | null;
  createdAt: Generated<Timestamp>;
  data: Json | null;
  deduplicationKey: string | null;
  emailedAt: Timestamp | null;
  id: Generated<string>;
  pageId: string | null;
  readAt: Timestamp | null;
  spaceId: string | null;
  type: string;
  userId: string;
  workspaceId: string;
}

export interface PageAccessRules {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  effect: string;
  groupId: string | null;
  id: Generated<string>;
  pageId: string;
  principalType: string;
  role: string | null;
  sourcePageId: string | null;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  userId: string | null;
  workspaceId: string;
}

export interface PageHistory {
  changeData: Json | null;
  changeType: string | null;
  content: Json | null;
  contributorIds: Generated<string[] | null>;
  coverPhoto: string | null;
  createdAt: Generated<Timestamp>;
  icon: string | null;
  id: Generated<string>;
  lastUpdatedById: string | null;
  pageId: string;
  slug: string | null;
  slugId: string | null;
  sourceBatchId: string | null;
  spaceId: string;
  title: string | null;
  updatedAt: Generated<Timestamp>;
  version: number | null;
  workspaceId: string;
}

export interface PageLabels {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  labelId: string;
  pageId: string;
}

export interface Pages {
  content: Json | null;
  contributorIds: Generated<string[] | null>;
  coverPhoto: string | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  databaseSearchText: Generated<string>;
  databaseSearchTsv: string | null;
  deletedAt: Timestamp | null;
  deletedById: string | null;
  icon: string | null;
  id: Generated<string>;
  isLocked: Generated<boolean>;
  lastUpdatedById: string | null;
  parentPageId: string | null;
  position: string | null;
  settings: Generated<Json | null>;
  slugId: string;
  spaceId: string;
  tagValues: Generated<string[]>;
  textContent: string | null;
  templateArchivedAt: Timestamp | null;
  templateKind: string | null;
  title: string | null;
  tsv: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
  ydoc: Buffer | null;
}

export interface PageTransclusionReferences {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  referencePageId: string;
  sourcePageId: string;
  transclusionId: string;
  workspaceId: string;
}

export interface PageTemplateWorkspacePolicies {
  createdAt: Generated<Timestamp>;
  enabled: Generated<boolean>;
  revision: Generated<number>;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  workspaceId: string;
}

export interface PageTemplateSpacePolicies {
  allowCreateTemplate: Generated<boolean>;
  allowRegularTemplate: Generated<boolean>;
  allowSyncedTemplate: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  revision: Generated<number>;
  spaceId: string;
  templatesEnabled: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  workspaceId: string;
}

export interface PageTemplateGroupPolicies {
  allowedActions: Json | null;
  createdAt: Generated<Timestamp>;
  groupId: string;
  id: Generated<string>;
  revision: Generated<number>;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  updatedById: string | null;
  workspaceId: string;
}

export interface PageTemplateOperations {
  afterContentHash: string | null;
  attachmentMapping: Json | null;
  attemptCount: Generated<number>;
  baseContentHash: string | null;
  consumerPageId: string | null;
  createdAt: Generated<Timestamp>;
  errorCode: string | null;
  id: Generated<string>;
  idempotencyKey: string;
  leaseToken: string | null;
  leaseExpiresAt: Timestamp | null;
  operationKind: string;
  requestHash: string;
  requestedById: string;
  resultPageId: string | null;
  sourcePageId: string | null;
  stagedContent: Json | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface PageTemplateRevisions {
  content: Json;
  contentHash: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  publishedById: string | null;
  revision: number;
  spaceId: string;
  templatePageId: string;
  workspaceId: string;
}

export interface PageTemplateInstances {
  appliedRevision: number | null;
  childPageId: string;
  createdAt: Generated<Timestamp>;
  createdRevision: number | null;
  detachedAt: Timestamp | null;
  detachedById: string | null;
  id: Generated<string>;
  instanceKind: string;
  lastErrorCode: string | null;
  spaceId: string;
  status: Generated<string>;
  templatePageId: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface PageTemplateSyncRuns {
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  errorCode: string | null;
  failedCount: Generated<number>;
  id: Generated<string>;
  leaseExpiresAt: Timestamp | null;
  leaseToken: string | null;
  processedCount: Generated<number>;
  requestedById: string | null;
  revision: number;
  revisionId: string;
  spaceId: string;
  startedAt: Timestamp | null;
  status: Generated<string>;
  succeededCount: Generated<number>;
  templatePageId: string;
  totalCount: Generated<number>;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface PageTemplateSyncItems {
  attemptCount: Generated<number>;
  childPageId: string;
  createdAt: Generated<Timestamp>;
  errorCode: string | null;
  id: Generated<string>;
  instanceId: string;
  runId: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface PageTemplateAttachmentMappings {
  childAttachmentId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  instanceId: string;
  sourceAttachmentId: string;
}

export interface PageTemplatePublishConfirmations {
  consumedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  draftHash: string;
  expiresAt: Timestamp;
  filledInstanceCount: Generated<number>;
  id: Generated<string>;
  removedFieldIds: Json;
  requestedById: string;
  templatePageId: string;
}

export interface PageTransclusions {
  content: Json;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  pageId: string;
  transclusionId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface PushNotificationJobs {
  createdAt: Generated<Timestamp>;
  eventsCount: Generated<number>;
  id: Generated<string>;
  idempotencyKey: string;
  leaseExpiresAt: Timestamp | null;
  leaseToken: string | null;
  pageId: string;
  payload: Json | null;
  revision: Generated<number>;
  sendAfter: Timestamp;
  sentAt: Timestamp | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  windowKey: string;
  workspaceId: string;
}

export interface PushSubscriptions {
  auth: string;
  createdAt: Generated<Timestamp>;
  endpoint: string;
  id: Generated<string>;
  lastSeenAt: Generated<Timestamp>;
  p256dh: string;
  revokedAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
  workspaceId: string;
}

export interface QueueOutbox {
  attemptCount: Generated<number>;
  availableAt: Generated<Timestamp>;
  cancelledAt: Timestamp | null;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  dedupeKey: string;
  failedAt: Timestamp | null;
  id: Generated<string>;
  kind: string;
  lastErrorCode: string | null;
  leaseExpiresAt: Timestamp | null;
  leaseToken: string | null;
  payload: Json;
  secretPayload: string | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface PageDuplicateAttachmentPins {
  createdAt: Generated<Timestamp>;
  outboxId: string;
  sourceAttachmentId: string;
}

export interface Shares {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  includeSubPages: Generated<boolean | null>;
  key: string;
  pageId: string | null;
  searchIndexing: Generated<boolean | null>;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface SpaceMembers {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  groupId: string | null;
  id: Generated<string>;
  role: string;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
}

export interface Spaces {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  defaultRole: Generated<string>;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  logo: string | null;
  name: string | null;
  settings: Json | null;
  slug: string;
  updatedAt: Generated<Timestamp>;
  visibility: Generated<string>;
  workspaceId: string;
}

export interface SsoLoginStates {
  authProviderId: string;
  codeVerifier: string | null;
  consumedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  nonce: string | null;
  purpose: Generated<string>;
  requestId: string | null;
  requestValue: string | null;
  returnTo: string | null;
  sessionId: string | null;
  spaceId: string | null;
  stateHash: string;
  userId: string | null;
  workspaceId: string;
}

export interface UserMfa {
  backupCodes: string[] | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isEnabled: Generated<boolean | null>;
  lastUsedTotpCounter: Int8 | null;
  method: Generated<string>;
  secret: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  deactivatedAt: Timestamp | null;
  deletedAt: Timestamp | null;
  email: string;
  emailVerifiedAt: Timestamp | null;
  hasGeneratedPassword: Generated<boolean>;
  id: Generated<string>;
  invitedById: string | null;
  lastActiveAt: Timestamp | null;
  lastLoginAt: Timestamp | null;
  locale: string | null;
  name: string | null;
  password: string | null;
  role: string | null;
  settings: Json | null;
  timezone: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string | null;
}

export interface UserSessions {
  createdAt: Generated<Timestamp>;
  deviceName: string | null;
  expiresAt: Timestamp;
  geoLocation: string | null;
  id: Generated<string>;
  ipAddress: string | null;
  lastActiveAt: Generated<Timestamp>;
  metadata: Json | null;
  mfaVerifiedAt: Timestamp | null;
  revokedAt: Timestamp | null;
  ssoAuthProviderId: string | null;
  ssoVerifiedAt: Timestamp | null;
  userAgent: string | null;
  userId: string;
  workspaceId: string;
}

export interface UserTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  token: string;
  type: string;
  usedAt: Timestamp | null;
  userId: string;
  workspaceId: string | null;
}

export interface Watchers {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  mutedAt: Timestamp | null;
  pageId: string | null;
  spaceId: string;
  type: string;
  userId: string;
  workspaceId: string;
}

export interface WorkspaceInvitations {
  createdAt: Generated<Timestamp>;
  email: string | null;
  expiresAt: Timestamp | null;
  groupIds: string[] | null;
  id: Generated<string>;
  invitedById: string | null;
  role: string;
  token: string | null;
  tokenHash: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Workspaces {
  createdAt: Generated<Timestamp>;
  customDomain: string | null;
  defaultRole: Generated<string>;
  defaultSpaceId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  emailDomains: Generated<string[] | null>;
  enforceMfa: Generated<boolean | null>;
  enforceSso: Generated<boolean>;
  hostname: string | null;
  id: Generated<string>;
  logo: string | null;
  name: string | null;
  pageHistoryRetentionDays: number | null;
  settings: Json | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  aiAgentToolVerifications: AiAgentToolVerifications;
  aiAssistantProfileGroupPolicies: AiAssistantProfileGroupPolicies;
  aiAssistantProfileMcpTools: AiAssistantProfileMcpTools;
  aiAssistantProfiles: AiAssistantProfiles;
  aiAssistantProfileUserPreferences: AiAssistantProfileUserPreferences;
  aiAssistantProfileWorkspaceSettings: AiAssistantProfileWorkspaceSettings;
  aiBuiltinToolSpacePolicies: AiBuiltinToolSpacePolicies;
  aiBuiltinToolWorkspacePolicies: AiBuiltinToolWorkspacePolicies;
  aiAuxRuns: AiAuxRuns;
  aiChatFiles: AiChatFiles;
  aiConversationContextSources: AiConversationContextSources;
  aiConversations: AiConversations;
  aiFileUploadBatches: AiFileUploadBatches;
  aiMcpGroupPolicies: AiMcpGroupPolicies;
  aiMcpServers: AiMcpServers;
  aiMcpSpaceBindings: AiMcpSpaceBindings;
  aiMcpUserPreferences: AiMcpUserPreferences;
  aiMcpWorkspaceSettings: AiMcpWorkspaceSettings;
  aiMessages: AiMessages;
  aiMessageSources: AiMessageSources;
  aiRunContextSources: AiRunContextSources;
  aiRuns: AiRuns;
  aiRunSourceDependencies: AiRunSourceDependencies;
  aiRunSteps: AiRunSteps;
  aiSpaceConfigs: AiSpaceConfigs;
  aiSpaceContentExclusions: AiSpaceContentExclusions;
  aiSpaceContentPolicies: AiSpaceContentPolicies;
  apiKeys: ApiKeys;
  attachmentCleanupBatches: AttachmentCleanupBatches;
  attachmentCleanupItems: AttachmentCleanupItems;
  attachments: Attachments;
  authAccounts: AuthAccounts;
  authProviderGroupMappings: AuthProviderGroupMappings;
  authProviderGroupMemberships: AuthProviderGroupMemberships;
  authProviders: AuthProviders;
  backlinks: Backlinks;
  comments: Comments;
  databaseCells: DatabaseCells;
  databaseProperties: DatabaseProperties;
  databaseRows: DatabaseRows;
  databases: Databases;
  databaseViews: DatabaseViews;
  dictionaryTermAliases: DictionaryTermAliases;
  dictionaryTerms: DictionaryTerms;
  favorites: Favorites;
  fileTaskImportArtifacts: FileTaskImportArtifacts;
  fileTaskImportPages: FileTaskImportPages;
  fileTasks: FileTasks;
  groups: Groups;
  groupUsers: GroupUsers;
  labels: Labels;
  notifications: Notifications;
  pageAccessRules: PageAccessRules;
  pageDuplicateAttachmentPins: PageDuplicateAttachmentPins;
  pageHistory: PageHistory;
  pageLabels: PageLabels;
  pages: Pages;
  pageTransclusionReferences: PageTransclusionReferences;
  pageTransclusions: PageTransclusions;
  pageTemplateGroupPolicies: PageTemplateGroupPolicies;
  pageTemplateAttachmentMappings: PageTemplateAttachmentMappings;
  pageTemplateInstances: PageTemplateInstances;
  pageTemplateOperations: PageTemplateOperations;
  pageTemplatePublishConfirmations: PageTemplatePublishConfirmations;
  pageTemplateRevisions: PageTemplateRevisions;
  pageTemplateSpacePolicies: PageTemplateSpacePolicies;
  pageTemplateSyncItems: PageTemplateSyncItems;
  pageTemplateSyncRuns: PageTemplateSyncRuns;
  pageTemplateWorkspacePolicies: PageTemplateWorkspacePolicies;
  pushNotificationJobs: PushNotificationJobs;
  pushSubscriptions: PushSubscriptions;
  queueOutbox: QueueOutbox;
  shares: Shares;
  spaceMembers: SpaceMembers;
  spaces: Spaces;
  ssoLoginStates: SsoLoginStates;
  userMfa: UserMfa;
  users: Users;
  userSessions: UserSessions;
  userTokens: UserTokens;
  watchers: Watchers;
  workspaceInvitations: WorkspaceInvitations;
  workspaces: Workspaces;
}
